#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "protocolo_telemetria.h"

typedef struct {
    bool valido;
    uint16_t sequencia;
    uint32_t tempo_mestre_ms;
    uint16_t tensao_adc_bruta;
    int16_t aceleracao_x;
    int16_t aceleracao_y;
    int16_t aceleracao_z;
    int16_t giroscopio_x;
    int16_t giroscopio_y;
    int16_t giroscopio_z;
    uint8_t marcha;
    bool simulado;
    uint16_t velocidade_centesimos_kmh;
    int16_t aceleracao_milesimos_ms2;
    uint16_t acelerador_decimos_percentual;
    uint16_t freio_decimos_percentual;
    uint16_t tensao_pacote_mv;
    int16_t corrente_centesimos_a;
    uint16_t carga_decimos_percentual;
    uint16_t tensoes_celulas_mv[4];
    int32_t latitude_micrograus;
    int32_t longitude_micrograus;
    uint16_t rumo_decimos_grau;
    uint16_t distancias_cm[8];
    int16_t potencia_w;
    uint16_t autonomia_decimos_km;
    uint32_t percurso_metros;
    uint32_t odometro_metros;
    uint32_t pacotes_validos;
    uint32_t pacotes_invalidos;
    uint32_t falhas_crc;
    uint32_t falhas_cabecalho;
    uint32_t falhas_conteudo;
    uint32_t pacotes_perdidos;
    uint32_t pacotes_duplicados;
    uint32_t reinicios_mestre;
    uint32_t ultimo_recebimento_ms;
    uint32_t intervalo_medio_ms;
    uint32_t jitter_medio_ms;
    uint32_t latencia_relativa_ms;
    uint32_t taxa_pacotes_centesimos_hz;
    uint32_t taxa_perda_centesimos_percentual;
} dados_telemetria_t;
